<?php
declare(strict_types=1);

namespace Pluck\Support;

use RuntimeException;

/**
 * Install-time configuration, held in data/settings/config.php.
 *
 * This is the one PHP file Pluck still writes at runtime, and it contains only
 * scalars produced by var_export() - never user content. Everything a visitor
 * or admin can type is stored as inert data instead.
 */
final class Config
{
	private const FILE = 'settings/config.php';

	/** @param array<string,scalar|null> $values */
	public function __construct(
		private readonly string $dataDir,
		private array $values = [],
	) {
	}

	public static function load(string $dataDir): self
	{
		$file = Path::within($dataDir, self::FILE);
		if (!is_file($file)) {
			return new self($dataDir);
		}

		/** @var mixed $values */
		$values = require $file;

		return new self($dataDir, is_array($values) ? $values : []);
	}

	public function exists(): bool
	{
		return is_file(Path::within($this->dataDir, self::FILE));
	}

	public function get(string $key, mixed $default = null): mixed
	{
		return $this->values[$key] ?? $default;
	}

	public function set(string $key, mixed $value): void
	{
		if ($value !== null && !is_scalar($value)) {
			throw new RuntimeException('Config only stores scalar values.');
		}
		$this->values[$key] = $value;
	}

	/** @return array<string,mixed> */
	public function all(): array
	{
		return $this->values;
	}

	public function save(): void
	{
		$file = Path::within($this->dataDir, self::FILE);
		$body = "<?php\n"
			. "// Generated by the Pluck installer. Safe to edit by hand; keys are documented in docs/CONFIG.md.\n"
			. "declare(strict_types=1);\n\n"
			. 'return ' . var_export($this->values, true) . ";\n";

		// Path::writeAtomic tells OPcache the file changed, which config.php needs
		// more than anything else Pluck writes: it is PHP, it is included on every
		// request, and a stale copy reads as a setting that will not save.
		Path::writeAtomic($file, $body);
	}
}
